### ISSUE TITLE
可以支持下图中的效果吗

### ISSUE THREAD

**Issue by Kenmmm** [iielse/RangeSeekBar#1]
![](http://ww1.sinaimg.cn/mw690/005yqym4gw1f7necf8g6kj30oz0633ys.jpg)

拖动的时候上面会像气泡那样,然后停止拖动停止显示

**Comment by iielse** [comment]
https://github.com/qiujuer/Genius-Android 
这个地址应该能帮到你，下载那个simple.apk里面的seekbar控件有你要的效果

**Comment by Kenmmm** [comment]
谢谢,我去看看
