### ISSUE TITLE
可以支持添加多个SeekBar 控制多个范围吗？

### ISSUE THREAD

**Issue by cjkiss** [iielse/RangeSeekBar#2]
在百度搜索“PPT中文本渐变效果：[3]渐变光圈的使用” 类似这样的效果

**Comment by iielse** [comment]
@cjkiss 很遗憾，SeekBar的数量没有提供可以改变的api。你的需求需要进行专门的 View定制。
http://blog.csdn.net/aigestudio/article/details/41212583
阅读并且学习以上文章后应该能够开始自行尝试。
